In [1]:
#import dependencies
import pandas as pd
import numpy as np
import csv

In [3]:
#use 2 csv files for this exercise & concatenate them.
#this one is from Jan 2019. 
Jan19 = pd.read_csv("citibike-tripdata.csv")
Jan19.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0

In [4]:
#2nd CSV, from Jan 2018 Citi Bike.
Jan18 = pd.read_csv("201801-citibike-tripdata.csv")
Jan18.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72,W 52 St & 11 Ave,40.767272,-73.993929,505,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1

In [5]:
#merge them together
df1 = pd.DataFrame(Jan18)
df2 = pd.DataFrame(Jan19)

Jan18_19_df = pd.concat([df1, df2])

Jan18_19_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72,W 52 St & 11 Ave,40.767272,-73.993929,505,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1

In [6]:
#Drop all rows where there's "NA"
Jan18_19_df.dropna(how='all')

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72,W 52 St & 11 Ave,40.767272,-73.993929,505,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1
5,1602,2018-01-01 21:31:54.1920,2018-01-01 21:58:36.3530,72,W 52 St & 11 Ave,40.767272,-73.993929,482,W 15 St & 7 Ave,40.739355,-73.999318,30106,Subscriber,1968,1
6,722,2018-01-02 07:54:53.6460,2018-01-02 08:06:55.8720,72,W 52 St & 11 Ave,40.767272,-73.993929,228,E 48 St & 3 Ave,40.754601,-73.971879,32059,Subscriber,1978,1
7,434,2018-01-02 08:06:14.3310,2018-01-02 08:13:28.7670,72,W 52 St & 11 Ave,40.767272,-73.993929,173,Broadway & W 49 St,40.760683,-73.984527,30525,Subscriber,1983,1
8,366,2018-01-02 08:10:15.2550,2018-01-02 08:16:21.8960,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,27439,Subscriber,1974,1
9,324,2018-01-02 08:13:30.8960,2018-01-02 08:18:55.1200,72,W 52 St & 11 Ave,40.767272,-73.993929,450,W 49 St & 8 Ave,40.762272,-73.987882,30892,Subscriber,1947,1
10,1155,2018-01-02 09:15:29.9050,2018-01-02 09:34:45.0200,72,W 52 St & 11 Ave,40.767272,-73.993929,347,Greenwich St & W Houston St,40.728846,-74.008591,31591,Subscriber,1982,1
11,1200,2018-01-02 10:23:18.8800,2018-01-02 10:43:18.9110,72,W 52 St & 11 Ave,40.767272,-73.993929,127,Barrow St & Hudson St,40.731724,-74.006744,30257,Subscriber,1974,1
12,732,2018-01-02 11:52:37.5540,2018-01-02 12:04:49.8800,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,32649,Subscriber,1969,1
13,600,2018-01-02 12:20:57.0070,2018-01-02 12:30:57.0180,72,W 52 St & 11 Ave,40.767272,-73.993929,457,Broadway & W 58 St,40.766953,-73.981693,26964,Subscriber,1991,1
14,1058,2018-01-02 13:28:46.1540,2018-01-02 13:46:24.3070,72,W 52 St & 11 Ave,40.767272,-73.993929,523,W 38 St & 8 Ave,40.754666,-73.991382,32617,Subscriber,1947,1
15,256,2018-01-02 13:54:11.6460,2018-01-02 13:58:28.1980,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,31095,Subscriber,1978,1
16,318,2018-01-02 13:55:11.9200,2018-01-02 14:00:29.9410,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,31182,Subscriber,1963,1
17,694,2018-01-02 14:27:49.6230,2018-01-02 14:39:24.1270,72,W 52 St & 11 Ave,40.767272,-73.993929,484,W 44 St & 5 Ave,40.755003,-73.980144,32375,Subscriber,1967,1
18,604,2018-01-02 15:04:41.3810,2018-01-02 15:14:45.7090,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,32505,Subscriber,1964,1
19,724,2018-01-02 15:25:00.5410,2018-01-02 15:37:05.3230,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,19512,Subscriber,1965,1
20,395,2018-01-02 15:37:55.9310,2018-01-02 15:44:31.0550,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,17881,Subscriber,1956,1
21,520,2018-01-02 16:09:21.1800,2018-01-02 16:18:02.0510,72,W 52 St & 11 Ave,40.767272,-73.993929,500,Broadway & W 51 St,40.762288,-73.983362,31426,Customer,1969,0
22,430,2018-01-02 16:10:59.3790,2018-01-02 16:18:10.0110,72,W 52 St & 11 Ave,40.767272,-73.993929,500,Broadway & W 51 St,40.762288,-73.983362,32349,Customer,1969,0
23,842,2018-01-02 16:34:16.2920,2018-01-02 16:48:18.6180,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,31019,Subscriber,1978,1
24,243,2018-01-02 16:36:12.6120,2018-01-02 16:40:15.7660,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,29984,Subscriber,1973,1
25,705,2018-01-02 16:36:14.3160,2018-01-02 16:47:59.7340,72,W 52 St & 11 Ave,40.767272,-73.993929,477,W 41 St & 8 Ave,40.756405,-73.990026,20922,Subscriber,1992,1
26,1163,2018-01-02 16:43:09.9290,2018-01-02 17:02:33.2530,72,W 52 St & 11 Ave,40.767272,-73.993929,3466,W 45 St & 6 Ave (OLD),40.756687,-73.982577,33277,Subscriber,1974,1
27,680,2018-01-02 16:58:34.7080,2018-01-02 17:09:55.0030,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,16425,Subscriber,1964,1
28,634,2018-01-02 17:04:25.6190,2018-01-02 17:14:59.7750,72,W 52 St & 11 Ave,40.767272,-73.993929,484,W 44 St & 5 Ave,40.755003,-73.980144,28382,Subscriber,1977,1
29,782,2018-01-02 17:13:04.4750,2018-01-02 17:26:06.8250,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,30649,Subscriber,1982,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19646,787,2019-01-02 16:05:54.8100,2019-01-02 16:19:02.2710,3694,Jackson Square,40.711130,-74.078900,3268,Lafayette Park,40.713464,-74.062859,29540,Subscriber,1991,2
19647,988,2019-01-03 06:24:05.2220,2019-01-03 06:40:33.9420,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29658,Subscriber,1977,1
19648,2692,2019-01-03 15:52:10.5060,2019-01-03 16:37:03.4000,3694,Jackson Square,40.711130,-74.078900,3268,Lafayette Park,40.713464,-74.062859,29605,Subscriber,1991,2
19649,235,2019-01-04 12:44:01.1470,2019-01-04 12:47:56.2510,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29259,Subscriber,1988,1
19650,1969,2019-01-04 15:17:55.7520,2019-01-04 15:50:45.2160,3694,Jackson Square,40.711130,-74.078900,3211,Newark Ave,40.721525,-74.046305,29570,Subscriber,1991,2
19651,565,2019-01-05 14:43:39.8780,2019-01-05 14:53:05.7420,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,26159,Subscriber,1995,1
19652,623,2019-01-06 19:51:20.6840,2019-01-06 20:01:44.6540,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26152,Subscriber,1983,2
19653,328,2019-01-07 12:08:43.2100,2019-01-07 12:14:11.4640,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29243,Subscriber,1991,1
19654,416,2019-01-07 16:50:31.6670,2019-01-07 16:57:28.6020,3694,Jackson Square,40.711130,-74.078900,3277,Communipaw & Berry Lane,40.714358,-74.066611,26237,Subscriber,1991,1
19655,2210,2019-01-08 15:51:37.3020,2019-01-08 16:28:28.0370,3694,Jackson Square,40.711130,-74.078900,3268,Lafayette Park,40.713464,-74.062859,29537,Subscriber,1991,2
19656,964,2019-01-09 13:19:48.4420,2019-01-09 13:35:53.0820,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,26171,Subscriber,1988,1
19657,833,2019-01-09 15:27:37.2150,2019-01-09 15:41:31.0400,3694,Jackson Square,40.711130,-74.078900,3206,Hilltop,40.731169,-74.057574,26303,Subscriber,1991,2
19658,767,2019-01-10 22:52:55.5680,2019-01-10 23:05:43.5000,3694,Jackson Square,40.711130,-74.078900,3677,Glenwood Ave,40.727551,-74.071061,26173,Customer,1998,2
19659,1059,2019-01-11 06:21:47.7880,2019-01-11 06:39:26.8030,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26184,Subscriber,1977,1
19660,273,2019-01-12 20:15:46.1420,2019-01-12 20:20:19.6890,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26303,Subscriber,1983,2
19661,1077,2019-01-14 06:28:39.1030,2019-01-14 06:46:36.6850,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29210,Subscriber,1977,1
19662,1053,2019-01-15 06:32:07.2770,2019-01-15 06:49:40.8450,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29548,Subscriber,1977,1
19663,107,2019-01-15 15:52:46.6240,2019-01-15 15:54:34.5790,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29295,Subscriber,1991,2
19664,830,2019-01-15 16:00:59.0470,2019-01-15 16:14:49.9750,3694,Jackson Square,40.711130,-74.078900,3206,Hilltop,40.731169,-74.057574,29295,Subscriber,1991,2
19665,1072,2019-01-16 06:15:37.3320,2019-01-16 06:33:29.4660,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29252,Subscriber,1977,1
19666,2605,2019-01-16 16:15:23.6090,2019-01-16 16:58:48.8510,3694,Jackson Square,40.711130,-74.078900,3211,Newark Ave,40.721525,-74.046305,26211,Subscriber,1991,2
19667,993,2019-01-17 06:28:22.9120,2019-01-17 06:44:56.6140,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29272,Subscriber,1977,1
19668,345,2019-01-18 12:25:29.4430,2019-01-18 12:31:14.9500,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29515,Subscriber,1983,1
19669,1146,2019-01-18 15:48:34.3690,2019-01-18 16:07:41.2500,3694,Jackson Square,40.711130,-74.078900,3211,Newark Ave,40.721525,-74.046305,29442,Subscriber,1991,2
19670,991,2019-01-25 06:19:31.8210,2019-01-25 06:36:03.2230,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29530,Subscriber,1977,1
19671,853,2019-01-26 06:40:17.3320,2019-01-26 06:54:30.8880,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26293,Subscriber,1977,1
19672,936,2019-01-27 06:36:20.6400,2019-01-27 06:51:57.1460,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26291,Subscriber,1977,1
19673,653,2019-01-27 21:14:08.5460,2019-01-27 21:25:01.6170,3694,Jackson Square,40.711130,-74.078900,3677,Glenwood Ave,40.727551,-74.071061,26188,Customer,1998,2
19674,960,2019-01-29 06:15:26.5880,2019-01-29 06:31:26.7300,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26196,Subscriber,1977,1
19675,1109,2019-01-30 06:30:03.6050,2019-01-30 06:48:33.2760,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26242,Subscriber,1977,1

In [7]:
#export to CSV
Jan18_19_df.to_csv("Jan18_19.csv", encoding='utf-8', index=False)